
// these are auto-generated by Wails
import { OpenFile, ReadFile, SaveFile, SaveFileAs, GetStartupFile, StartWatching, StopWatching, CheckForUpdates } from '../wailsjs/go/main/App.js';
import { EventsOn, BrowserOpenURL } from '../wailsjs/runtime/runtime.js';

(function() {
  'use strict';

  // ── State ──────────────────────────────────────────────
  var files = [];
  var active = -1;
  var view = 'split';
  var srchMatches = [], srchIdx = 0;
  var dragN = 0;

  // ── DOM refs ───────────────────────────────────────────
  var ED = document.getElementById('ed');
  var LN = document.getElementById('ln');
  var PW = document.getElementById('pw');
  var PV = document.getElementById('pv');
  var EW = document.getElementById('ew');
  var RZ = document.getElementById('rz');
  var EMP = document.getElementById('emp');
  var FTB = document.getElementById('ftb');
  var SRCH = document.getElementById('srch');
  var SI = document.getElementById('si');
  var SC = document.getElementById('sc');
  var FLIST = document.getElementById('flist');
  var FNAME = document.getElementById('fname');
  var DIRTY = document.getElementById('dirty');
  var TST = document.getElementById('tst');
  var DOV = document.getElementById('dov');
  var OUTLINE_RESIZE = document.getElementById('outline-resize');
  var NOTIF = document.getElementById('notif');
  var NOTIF_MSG = document.getElementById('notif-msg');
  var notifPath = '';
  var notifIdx = -1;
  var UPDATE_BAR = document.getElementById('update-bar');
  var UPDATE_MSG = document.getElementById('update-msg');
  var UPDATE_DESC = document.getElementById('update-desc');
  var updateUrl = '';
  var SB_VERSION = document.getElementById('sb-version');

  // ── Open files ─────────────────────────────────────────
  async function openPicker() {
    try {
      // call Go → shows native Windows file dialog
      var path = await OpenFile();

      // user cancelled dialog
      if (!path) return;

      // call Go → read file content from disk
      var content = await ReadFile(path);

      // extract just the filename from full path
      var name = path.split(/[\\/]/).pop();

      // check if already open
      var idx = files.findIndex(function(x){ return x.path === path; });
      if (idx >= 0) {
        // already open, just switch to it
        setActive(idx);
        toast(name + ' is already open');
        return;
      }

      // add to files list
      files.push({ name: name, content: content, dirty: false, path: path });
      StartWatching(path);
      setActive(files.length - 1);
      renderSidebar();
      toast('Opened ' + name);

    } catch(err) {
      toast('Error opening file: ' + err);
    }
  }

  // ── New file ───────────────────────────────────────────
  function newFile() {
    var name = 'Untitled-' + (files.length + 1) + '.md';
    var content = '# ' + name.replace('.md','') + '\n\nStart writing here…\n';
    files.push({name: name, content: content, dirty: true});
    setActive(files.length - 1);
    renderSidebar();
    toast('Created ' + name);
  }

  // ── Close file ─────────────────────────────────────────
  function closeFile(idx) {
    if(files[idx].dirty && !confirm('Unsaved changes in "' + files[idx].name + '". Close anyway?')) return;
    if(files[idx].path) StopWatching(files[idx].path);
    files.splice(idx, 1);
    if(files.length === 0){ active = -1; showEmpty(); }
    else setActive(Math.min(idx, files.length - 1));
    renderSidebar();
  }

  // ── Save file ──────────────────────────────────────────
  async function saveFile() {
    if(active < 0) return;
    var f = files[active];
    try {
        if(f.path) {
        // file already has a path → save directly to disk
        await SaveFile(f.path, f.content);
        f.dirty = false;
        updateTitle();
        renderSidebar();
        toast('Saved ' + f.name);
        } else {
        // new file, no path yet → show Save As dialog
        var savedPath = await SaveFileAs(f.content);
        if(savedPath) {
            f.path = savedPath;
            f.name = savedPath.split(/[\\/]/).pop();
            f.dirty = false;
            updateTitle();
            renderSidebar();
            toast('Saved ' + f.name);
        }
        }
    } catch(err) {
        toast('Error saving: ' + err);
    }
  }
  // ── Save file as ────────────────────────────────────────
  async function saveFileAs() {
    if(active < 0) return;
    var f = files[active];
    
    try {
        var savedPath = await SaveFileAs(f.content);
        if(savedPath) {
        f.path = savedPath;
        f.name = savedPath.split(/[\\/]/).pop();
        f.dirty = false;
        updateTitle();
        renderSidebar();
        toast('Saved ' + f.name);
        }
    } catch(err) {
        toast('Error saving file: ' + err);
    }
  }

  // ── Set active file ────────────────────────────────────
  function setActive(idx) {
    active = idx;
    ED.value = files[idx].content;
    renderSidebar();
    updateTitle();
    updateLineNums();
    updateStatus();
    renderPreview();
    renderOutline();
    showEditorArea();
    ED.focus();
  }

function showEmpty() {
    EMP.style.display = 'flex';
    EW.style.display = 'none';
    PW.style.display = 'none';
    RZ.style.display = 'none';
    FNAME.textContent = 'No file open';
    DIRTY.style.display = 'none';
    FTB.style.opacity = '.35';
    FTB.style.pointerEvents = 'none';
    document.getElementById('sb-mode').textContent = 'No file';
 }

  function showEditorArea() {
    EMP.style.display = 'none';
    FTB.style.opacity = '';
    FTB.style.pointerEvents = '';
    applyView();
  }

  // ── Sidebar ────────────────────────────────────────────
  function renderSidebar() {
    FLIST.innerHTML = '';
    files.forEach(function(f, i){
      var div = document.createElement('div');
      div.className = 'fi' + (i === active ? ' act' : '');

      var icon = document.createElementNS('http://www.w3.org/2000/svg','svg');
      icon.setAttribute('width','12'); icon.setAttribute('height','12');
      icon.setAttribute('fill','none'); icon.setAttribute('viewBox','0 0 24 24');
      icon.setAttribute('stroke','currentColor'); icon.setAttribute('stroke-width','1.5');
      icon.style.flexShrink = '0'; icon.style.opacity = '.6';
      icon.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"/>';

      var nm = document.createElement('span');
      nm.className = 'fn';
      nm.textContent = f.name + (f.dirty ? ' ●' : '');

      var cl = document.createElement('button');
      cl.className = 'fx';
      cl.title = 'Close';
      cl.textContent = '✕';
      cl.setAttribute('data-idx', i);

      div.appendChild(icon);
      div.appendChild(nm);
      div.appendChild(cl);
      div.setAttribute('data-idx', i);
      FLIST.appendChild(div);
    });

    // attach events after render
    FLIST.querySelectorAll('.fi').forEach(function(el){
      var idx = parseInt(el.getAttribute('data-idx'));
      el.addEventListener('click', function(e){
        if(e.target.classList.contains('fx')) return;
        setActive(idx);
      });
    });
    FLIST.querySelectorAll('.fx').forEach(function(btn){
      var idx = parseInt(btn.getAttribute('data-idx'));
      btn.addEventListener('click', function(e){
        e.stopPropagation();
        closeFile(idx);
      });
    });
  }

  function updateTitle() {
    if(active < 0) return;
    var f = files[active];
    FNAME.textContent = f.name;
    DIRTY.style.display = f.dirty ? 'inline' : 'none';
  }

  // ── Editor events ──────────────────────────────────────
  ED.addEventListener('input', function(){
    if(active < 0) return;
    files[active].content = ED.value;
    files[active].dirty = true;
    updateTitle();
    renderSidebar();
    updateLineNums();
    updateStatus();
    renderPreview();
    renderOutline();
  });

  ED.addEventListener('keydown', function(e){
    // Tab
    if(e.key === 'Tab'){
      e.preventDefault();
      var s = ED.selectionStart, en = ED.selectionEnd;
      ED.setRangeText('  ', s, en, 'end');
      ED.dispatchEvent(new Event('input'));
      return;
    }
    // Ctrl+S
    if((e.ctrlKey||e.metaKey) && e.key === 's'){ e.preventDefault(); saveFile(); return; }
    // Ctrl+B
    if((e.ctrlKey||e.metaKey) && e.key === 'b'){ e.preventDefault(); fmt('bold'); return; }
    // Ctrl+I
    if((e.ctrlKey||e.metaKey) && e.key === 'i'){ e.preventDefault(); fmt('italic'); return; }
    // Ctrl+F
    if((e.ctrlKey||e.metaKey) && e.key === 'f'){ e.preventDefault(); toggleSearch(); return; }
    // Arrow keys for scrolling preview
    if(e.key === 'ArrowUp' || e.key === 'ArrowDown'){
      if(view === 'preview'){
        e.preventDefault();
        PW.scrollTop += e.key === 'ArrowDown' ? 50 : -50;
        return;
      }
    }

    // Smart Enter
    if(e.key === 'Enter'){
      var s = ED.selectionStart;
      var val = ED.value;
      var lineStart = val.lastIndexOf('\n', s-1) + 1;
      var line = val.slice(lineStart, s);
      var task  = line.match(/^(\s*)([-*+] \[[ x]\] )(.*)/);
      var ul    = line.match(/^(\s*)([-*+] )(.*)/);
      var ol    = line.match(/^(\s*)(\d+)\. (.*)/);
      if(task){
        e.preventDefault();
        if(task[3] === ''){ ED.value = val.slice(0,lineStart) + val.slice(s); ED.selectionStart = ED.selectionEnd = lineStart; }
        else { ED.setRangeText('\n' + task[1] + '- [ ] ', s, s, 'end'); }
        ED.dispatchEvent(new Event('input')); return;
      }
      if(ul && !task){
        e.preventDefault();
        if(ul[3] === ''){ ED.value = val.slice(0,lineStart) + val.slice(s); ED.selectionStart = ED.selectionEnd = lineStart; }
        else { ED.setRangeText('\n' + ul[1] + ul[2], s, s, 'end'); }
        ED.dispatchEvent(new Event('input')); return;
      }
      if(ol){
        e.preventDefault();
        if(ol[3] === ''){ ED.value = val.slice(0,lineStart) + val.slice(s); ED.selectionStart = ED.selectionEnd = lineStart; }
        else { ED.setRangeText('\n' + ol[1] + (parseInt(ol[2])+1) + '. ', s, s, 'end'); }
        ED.dispatchEvent(new Event('input')); return;
      }
    }
  });

  ED.addEventListener('scroll', function(){
    if(view !== 'split') return;
    var ratio = ED.scrollTop / Math.max(1, ED.scrollHeight - ED.clientHeight);
    PW.scrollTop = ratio * (PW.scrollHeight - PW.clientHeight);
  });

  ED.addEventListener('keyup', updateStatus);
  ED.addEventListener('click', updateStatus);

  function updateLineNums() {
    var n = ED.value.split('\n').length;
    var s = '';
    for(var i=1;i<=n;i++) s += i + '\n';
    LN.textContent = s;
  }

  function updateStatus() {
    if(active < 0) return;
    var val = ED.value;
    var lines = val.split('\n').length;
    var words = val.trim() === '' ? 0 : val.trim().split(/\s+/).length;
    var pos = ED.selectionStart;
    var before = val.slice(0, pos);
    var ln = before.split('\n').length;
    var col = pos - before.lastIndexOf('\n');
    document.getElementById('sb-mode').textContent = files[active].name;
    document.getElementById('sb-w').textContent = words + ' words';
    document.getElementById('sb-l').textContent = lines + ' lines';
    document.getElementById('sb-p').textContent = 'Ln ' + ln + ', Col ' + col;
  }

  // ── Format commands ────────────────────────────────────
  function fmt(type) {
    if(active < 0) return;
    var s = ED.selectionStart, en = ED.selectionEnd;
    var sel = ED.value.slice(s, en);

    switch(type){
      case 'bold':
        ED.setRangeText('**'+(sel||'bold text')+'**', s, en, 'select');
        break;
      case 'italic':
        ED.setRangeText('_'+(sel||'italic text')+'_', s, en, 'select');
        break;
      case 'strike':
        ED.setRangeText('~~'+(sel||'strikethrough')+'~~', s, en, 'select');
        break;
      case 'code':
        ED.setRangeText('`'+(sel||'code')+'`', s, en, 'select');
        break;
      case 'link':
        var url = prompt('Enter URL:', 'https://');
        if(!url) return;
        ED.setRangeText('['+(sel||'link text')+']('+ url +')', s, en, 'select');
        break;
      case 'h1': linePrefix('# '); return;
      case 'h2': linePrefix('## '); return;
      case 'h3': linePrefix('### '); return;
      case 'ul':   linePrefix('- '); return;
      case 'ol':   linePrefix('1. '); return;
      case 'task': linePrefix('- [ ] '); return;
      case 'quote': linePrefix('> '); return;
      case 'hr':
        ED.setRangeText('\n\n---\n\n', s, en, 'end');
        break;
      case 'codeblock':
        var lang = prompt('Language (optional, e.g. js, python):', '') || '';
        ED.setRangeText('\n```' + lang + '\n' + (sel || 'code here') + '\n```\n', s, en, 'end');
        break;
      case 'table':
        var rows = parseInt(prompt('Number of rows (including header):', '3') || '3');
        var cols = parseInt(prompt('Number of columns:', '3') || '3');
        var t = '\n';
        var headers = [];
        for(var c=1;c<=cols;c++) headers.push('Col ' + c);
        t += '| ' + headers.join(' | ') + ' |\n';
        var seps = [];
        for(var c=0;c<cols;c++) seps.push('---');
        t += '| ' + seps.join(' | ') + ' |\n';
        for(var r=1;r<rows;r++){
          var cells = [];
          for(var c=0;c<cols;c++) cells.push('   ');
          t += '| ' + cells.join(' | ') + ' |\n';
        }
        ED.setRangeText(t, s, en, 'end');
        break;
      default: return;
    }
    ED.dispatchEvent(new Event('input'));
  }

  function linePrefix(prefix) {
    var s = ED.selectionStart, en = ED.selectionEnd;
    var val = ED.value;
    var lineStart = val.lastIndexOf('\n', s-1) + 1;
    var lineEnd = val.indexOf('\n', en);
    if(lineEnd === -1) lineEnd = val.length;
    var block = val.slice(lineStart, lineEnd);

    var newBlock = block.split('\n').map(function(l){
      return l.startsWith(prefix) ? l.slice(prefix.length) : prefix + l;
    }).join('\n');

    ED.setRangeText(newBlock, lineStart, lineEnd, 'preserve');
    ED.dispatchEvent(new Event('input'));
  }

  // ── View modes ─────────────────────────────────────────
  function setView(v) {
    view = v;
    ['edit','split','preview'].forEach(function(m){
      document.getElementById('vt-'+m).classList.toggle('on', m === v);
    });
    if(active >= 0){ applyView(); renderPreview(); }
  }

  function applyView() {
    if(view === 'edit'){
      EW.style.display = 'flex'; EW.style.flex = '1';
      PW.style.display = 'none'; RZ.style.display = 'none';
    } else if(view === 'preview'){
      EW.style.display = 'none';
      PW.style.display = 'block'; PW.style.flex = '1'; PW.style.borderLeft = 'none';
      RZ.style.display = 'none';
    } else {
      EW.style.display = 'flex'; EW.style.flex = '1';
      PW.style.display = 'block'; PW.style.flex = '1'; PW.style.borderLeft = '1px solid var(--border)';
      RZ.style.display = 'block';
    }
  }

  // ── Resizer ────────────────────────────────────────────
  var rDragging = false, rX0 = 0, rW0 = 0;
  RZ.addEventListener('mousedown', function(e){
    rDragging = true; rX0 = e.clientX; rW0 = EW.offsetWidth;
    RZ.classList.add('on');
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
  });

  document.addEventListener('mousemove', function(e){
    if(!rDragging) return;
    var total = document.getElementById('ca').offsetWidth - 4;
    var nw = Math.max(180, Math.min(total - 180, rW0 + (e.clientX - rX0)));
    EW.style.flex = 'none'; EW.style.width = nw + 'px';
    PW.style.flex = '1';
  });

  document.addEventListener('mouseup', function(){
    if(!rDragging) return;
    rDragging = false; RZ.classList.remove('on');
    document.body.style.cursor = ''; document.body.style.userSelect = '';
  });

  // ── Outline resize ───────────────────────────────────────
  var oDragging = false, oY0 = 0, oH0 = 0;
  OUTLINE_RESIZE.addEventListener('mousedown', function(e){
    oDragging = true; oY0 = e.clientY; oH0 = FLIST.offsetHeight;
    OUTLINE_RESIZE.classList.add('on');
    document.body.style.cursor = 'row-resize';
    document.body.style.userSelect = 'none';
    e.preventDefault();
  });

  document.addEventListener('mousemove', function(e){
    if(!oDragging) return;
    var sb = document.getElementById('sb');
    var total = sb.offsetHeight - 80; // account for headers
    var nh = Math.max(100, Math.min(total - 100, oH0 + (e.clientY - oY0)));
    FLIST.style.flex = 'none'; FLIST.style.height = nh + 'px';
  });

  document.addEventListener('mouseup', function(){
    if(!oDragging) return;
    oDragging = false; OUTLINE_RESIZE.classList.remove('on');
    document.body.style.cursor = ''; document.body.style.userSelect = '';
  });

  // ── Search ─────────────────────────────────────────────
  function toggleSearch() {
    if(SRCH.classList.contains('on')){
      SRCH.classList.remove('on'); SI.value = ''; SC.textContent = ''; srchMatches = []; ED.focus();
    } else {
      SRCH.classList.add('on'); SI.focus();
    }
  }
  
  SI.addEventListener('input', runSearch);
  SI.addEventListener('keydown', function(e){
    if(e.key === 'Escape'){ toggleSearch(); return; }
    if(e.key === 'Enter'){
      e.preventDefault();
      if(!srchMatches.length) return;
      srchIdx = (srchIdx + (e.shiftKey ? srchMatches.length-1 : 1)) % srchMatches.length;
      SC.textContent = (srchIdx+1) + ' / ' + srchMatches.length;
      jumpMatch(srchIdx);
    }
  });
  document.getElementById('srch-close').addEventListener('click', toggleSearch);

  function runSearch() {
    var q = SI.value; srchMatches = [];
    if(!q){ SC.textContent = ''; return; }
    var text = ED.value.toLowerCase(), ql = q.toLowerCase(), i = 0;
    while(true){ var idx = text.indexOf(ql, i); if(idx<0) break; srchMatches.push(idx); i = idx+1; }
    srchIdx = 0;
    SC.textContent = srchMatches.length ? '1 / ' + srchMatches.length : 'No results';
  }
  function jumpMatch(i) {
    var q = SI.value, pos = srchMatches[i];
    ED.focus(); ED.setSelectionRange(pos, pos + q.length);
    var lh = 22, line = ED.value.slice(0, pos).split('\n').length;
    ED.scrollTop = Math.max(0, (line-3)*lh);
  }

  // ── Markdown renderer ──────────────────────────────────
  function renderPreview() {
    if(view === 'edit') return;
    var md = active >= 0 ? files[active].content : '';
    PV.innerHTML = mdToHtml(md);
    // wire checkboxes
    var cbs = PV.querySelectorAll('input[type=checkbox]');
    cbs.forEach(function(cb, i){
      cb.addEventListener('change', function(){
        var count = 0;
        var src = ED.value.replace(/- \[([ x])\]/g, function(m, c){
          if(count++ === i) return '- [' + (cb.checked ? 'x' : ' ') + ']';
          return m;
        });
        ED.value = src;
        files[active].content = src;
        files[active].dirty = true;
        updateTitle();
        renderSidebar();
        renderOutline();
      });
    });
  }

  // ── Preview copy shortcut ────────────────────────────────
  document.addEventListener('copy', function(e){
    var selection = window.getSelection();
    if(selection.rangeCount > 0 && PV.contains(selection.anchorNode)){
      var selectedText = selection.toString();
      if(selectedText){
        e.clipboardData.setData('text/plain', selectedText);
        e.preventDefault();
        toast('Copied to clipboard');
      }
    }
  });

  function renderOutline() {
    var outline = document.getElementById('outline');
    if(!outline) return;

    // get all lines from editor
    var lines = ED.value.split('\n');
    var headings = [];

    // find lines that start with #
    lines.forEach(function(line, i) {
        var match = line.match(/^(#{1,6}) (.+)/);
        if(match) {
        headings.push({
            level: match[1].length,  
            text:  match[2].trim(),  
            index: i                 
        });
        }
    });

    // clear current outline
    outline.innerHTML = '';

    // if no headings found
    if(headings.length === 0) {
        var empty = document.createElement('div');
        empty.style.cssText = 'padding:12px;font-size:12px;color:var(--text3);text-align:center';
        empty.textContent = 'No headings found';
        outline.appendChild(empty);
        return;
    }

    // build outline items
    headings.forEach(function(h, i) {
        var div = document.createElement('div');
        div.className = 'outline-item level-' + h.level;
        div.textContent = h.text;
        div.setAttribute('data-index', i);

        // click → scroll preview to that heading
        div.addEventListener('click', function() {
        // find matching heading in preview
        var pvHeadings = PV.querySelectorAll('h1,h2,h3,h4,h5,h6');
        if(pvHeadings[i]) {
            pvHeadings[i].scrollIntoView({ behavior: 'smooth', block: 'start' });
        }

        // also highlight active item
        outline.querySelectorAll('.outline-item').forEach(function(el){
            el.style.borderLeftColor = 'transparent';
            el.style.color = '';
        });
        div.style.borderLeftColor = 'var(--accent)';
        div.style.color = 'var(--accent)';
        });

        outline.appendChild(div);
    });
    }

  function esc(s){ return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

  function mdToHtml(md) {
    // protect fenced code blocks
    var cbs = [];
    md = md.replace(/```(\w*)\n?([\s\S]*?)```/g, function(_,lang,code){
      cbs.push({lang:lang, code:code});
      return '\x00CB'+(cbs.length-1)+'\x00';
    });
    // protect inline code
    var ics = [];
    md = md.replace(/`([^`\n]+)`/g, function(_,code){
      ics.push(code); return '\x00IC'+(ics.length-1)+'\x00';
    });

    // tables
    md = md.replace(/^(\|.+\|\n)(\|[-: |]+\|\n)((?:\|.+\|[ \t]*\n?)*)/gm, function(_,hdr,sep,body){
      function prow(r){ return r.trim().replace(/^\||\|$/g,'').split('|').map(function(c){return c.trim();}); }
      var aligns = prow(sep).map(function(c){ return c.startsWith(':')&&c.endsWith(':')? 'center': c.endsWith(':')? 'right': 'left'; });
      var ths = prow(hdr).map(function(c,i){ return '<th style="text-align:'+aligns[i]+'">' + inl(esc(c)) + '</th>'; }).join('');
      var rows = body.trim().split('\n').filter(function(r){return r.trim();}).map(function(r){
        return '<tr>'+prow(r).map(function(c,i){ return '<td style="text-align:'+aligns[i]+'">' + inl(esc(c)) + '</td>'; }).join('')+'</tr>';
      }).join('');
      return '<table><thead><tr>'+ths+'</tr></thead><tbody>'+rows+'</tbody></table>\n';
    });

    // headings
    md = md.replace(/^(#{1,6}) (.+)$/gm, function(_,h,t){ return '<h'+h.length+'>'+inl(esc(t))+'</h'+h.length+'>'; });
    // hr
    md = md.replace(/^[-*_]{3,}$/gm, '<hr>');
    // blockquote
    md = md.replace(/^(> ?.+(> ?.+)*)/gm, function(_,block){
      var inner = block.replace(/^> ?/gm,'');
      return '<blockquote>'+inl(esc(inner))+'</blockquote>';
    });

    // lists & paragraphs
    var lines = md.split('\n');
    var out = '';
    var inUL = false, inOL = false;

    for(var i=0;i<lines.length;i++){
      var line = lines[i];
      var cbm = line.match(/\x00CB(\d+)\x00/);
      if(cbm){
        if(inUL){out+='</ul>';inUL=false;} if(inOL){out+='</ol>';inOL=false;}
        var cb = cbs[parseInt(cbm[1])];
        out += '<pre><code>' + hlCode(esc(cb.code), cb.lang) + '</code></pre>';
        continue;
      }
      var task = line.match(/^(\s*)([-*+]) \[([ x])\] (.+)/);
      var ul   = !task && line.match(/^(\s*)([-*+]) (.+)/);
      var ol   = line.match(/^(\s*)(\d+)\. (.+)/);
      if(task){
        if(inOL){out+='</ol>';inOL=false;}
        if(!inUL){out+='<ul style="list-style:none;padding-left:1.5em">';inUL=true;}
        out += '<li class="tli"><input type="checkbox"'+(task[3]==='x'?' checked':'')+' readonly> '+inl(esc(task[4]))+'</li>';
      } else if(ul){
        if(inOL){out+='</ol>';inOL=false;}
        if(!inUL){out+='<ul>';inUL=true;}
        out += '<li>'+inl(esc(ul[3]))+'</li>';
      } else if(ol){
        if(inUL){out+='</ul>';inUL=false;}
        if(!inOL){out+='<ol>';inOL=true;}
        out += '<li>'+inl(esc(ol[3]))+'</li>';
      } else {
        if(inUL){out+='</ul>';inUL=false;} if(inOL){out+='</ol>';inOL=false;}
        if(line.trim()==='') out += '<br>';
        else if(line.match(/^<[a-z]/i)) out += line;
        else out += '<p>'+inl(esc(line))+'</p>';
      }
    }
    if(inUL) out+='</ul>'; if(inOL) out+='</ol>';

    // restore inline code
    out = out.replace(/\x00IC(\d+)\x00/g, function(_,i){ return '<code>'+esc(ics[parseInt(i)])+'</code>'; });
    return out;
  }

  function inl(s) {
    s = s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');
    s = s.replace(/__(.+?)__/g,'<strong>$1</strong>');
    s = s.replace(/\*([^*\n]+)\*/g,'<em>$1</em>');
    s = s.replace(/_([^_\n]+)_/g,'<em>$1</em>');
    s = s.replace(/~~(.+?)~~/g,'<del>$1</del>');
    s = s.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1">');
    s = s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');
    return s;
  }

function hlCode(code, lang) {
  if(!lang || lang === 'text') return code;

  var kws = {
    js:   /\b(const|let|var|function|return|if|else|for|while|do|switch|case|break|continue|class|new|this|typeof|instanceof|import|export|from|default|async|await|null|undefined|true|false|try|catch|finally|throw|of|in|delete|void)\b/g,
    ts:   /\b(const|let|var|function|return|if|else|for|while|class|new|this|typeof|instanceof|import|export|from|default|async|await|null|undefined|true|false|type|interface|enum|extends|implements|readonly|string|number|boolean|any|void)\b/g,
    py:   /\b(def|class|return|if|elif|else|for|while|import|from|as|with|try|except|finally|raise|pass|break|continue|and|or|not|in|is|lambda|yield|True|False|None|self|print)\b/g,
    sh:   /\b(echo|cd|ls|mkdir|rm|cp|mv|grep|cat|sed|awk|curl|wget|sudo|chmod|export|source|if|then|fi|else|for|do|done|while)\b/g,
    bash: /\b(echo|cd|ls|mkdir|rm|cp|mv|grep|cat|sed|awk|curl|wget|sudo|chmod|export|source|if|then|fi|else|for|do|done|while)\b/g,
    css:  /\b(color|background|margin|padding|font|border|display|position|width|height|flex|grid|transform|transition|animation|content|overflow|z-index|opacity)\b/g,
    env:  /^([A-Z_]+)(?==)/gm,
  };

  // step 1 — protect comments FIRST (single line only, not URLs)
  // for env/config files use # comments only
  var isEnv = !kws[lang];
  var protected_spans = [];

  function protect(html) {
    protected_spans.push(html);
    return '\x01SPAN' + (protected_spans.length - 1) + '\x01';
  }

  // comments first — but NOT // inside strings or URLs
  if(lang === 'py' || lang === 'sh' || lang === 'bash' || isEnv) {
    // hash comments only
    code = code.replace(/#[^\n]*/g, function(m){
      return protect('<span class="cc">' + m + '</span>');
    });
  } else if(lang === 'css') {
    // css block comments
    code = code.replace(/\/\*[\s\S]*?\*\//g, function(m){
      return protect('<span class="cc">' + m + '</span>');
    });
  } else {
    // js/ts — only // at start of line or after whitespace (not in URLs)
    code = code.replace(/(^|\s)(\/\/[^\n]*)/gm, function(_, pre, cmt){
      return pre + protect('<span class="cc">' + cmt + '</span>');
    });
  }

  // step 2 — strings (quoted values)
  code = code.replace(/(["'])((?:\\.|(?!\1)[^\\])*)\1/g, function(m){
    return protect('<span class="cs">' + m + '</span>');
  });

  // step 3 — numbers
  code = code.replace(/\b(\d+\.?\d*)\b/g, function(m){
    return protect('<span class="cn">' + m + '</span>');
  });

  // step 4 — keywords (only if not already inside a protected span)
  var kw = kws[lang];
  if(kw) {
    code = code.replace(kw, function(m){
      return protect('<span class="ckw">' + m + '</span>');
    });
  }

  // step 5 — function names
  code = code.replace(/\b([a-zA-Z_]\w*)\s*(?=\()/g, function(m, name){
    return protect('<span class="cf">' + name + '</span>') + m.slice(name.length);
  });

  // step 6 — env file keys (KEY=value)
  if(lang === 'env') {
    code = code.replace(/^([A-Z_][A-Z0-9_]*)(?==)/gm, function(m){
      return protect('<span class="ckw">' + m + '</span>');
    });
  }

  // restore all protected spans
  code = code.replace(/\x01SPAN(\d+)\x01/g, function(_, i){
    return protected_spans[parseInt(i)];
  });

  return code;
}

  // ── Toast ──────────────────────────────────────────────
  var tTimer;
  function toast(msg) {
    TST.textContent = msg;
    TST.classList.add('on');
    clearTimeout(tTimer);
    tTimer = setTimeout(function(){ TST.classList.remove('on'); }, 2000);
  }

  // ── Notification bar ───────────────────────────────────
  function showNotif(path, idx) {
    notifPath = path;
    notifIdx = idx;
    var name = path.split(/[\\/]/).pop();
    NOTIF_MSG.textContent = name + ' was modified outside this editor.';
    NOTIF.classList.add('on');
  }

  function hideNotif() {
    NOTIF.classList.remove('on');
    notifPath = '';
    notifIdx = -1;
  }

  // ── Update check ─────────────────────────────────────────
  function showUpdateBar(version, url, description) {
    UPDATE_MSG.textContent = 'Markit ' + version + ' is available!';
    UPDATE_DESC.innerHTML = description ? mdToHtml(description) : 'A new version is available for download.';
    updateUrl = url;
    UPDATE_BAR.classList.add('on');
  }

  function hideUpdateBar() {
    UPDATE_BAR.classList.remove('on');
    updateUrl = '';
  }

  async function checkForUpdates() {
    try {
      var currentVersion = '1.7.0';
      console.log('Checking for updates. Current version:', currentVersion);
      var result = await CheckForUpdates(currentVersion);
      console.log('Update check result:', result);
      if(result.hasUpdate) {
        showUpdateBar(result.version, result.url, result.description);
      } else {
        console.log('No update available');
      }
    } catch(err) {
      console.error('Update check failed:', err);
    }
  }

  // ── Sidebar toggle ─────────────────────────────────────
var sidebarOpen = localStorage.getItem('sidebarOpen') !== 'false';

function applySidebar() {
  var sb = document.getElementById('sb');
  var btn = document.getElementById('btn-sidebar');
  if(sidebarOpen) {
    sb.classList.remove('collapsed');
    btn.classList.add('active');
  } else {
    sb.classList.add('collapsed');
    btn.classList.remove('active');
  }
  localStorage.setItem('sidebarOpen', sidebarOpen);
}

function toggleSidebar() {
  sidebarOpen = !sidebarOpen;
  applySidebar();
}

// --- zoom in/zoom out -------------------------------------
let currentZoom = 1.0; // 1.0 == 100%

function changeZoom(amount) {
    // Update the zoom level variable
    currentZoom += amount;

    // Set limits to prevent infinite zooming (Min: 50%, Max: 250%)
    if (currentZoom < 0.5) currentZoom = 0.5;
    if (currentZoom > 2.5) currentZoom = 2.5;

    applyZoom();
}

function resetZoom() {
    currentZoom = 1.0;
    applyZoom();
}

function applyZoom() {
    const body = document.body;

    // Check if the browser supports the standard 'zoom' property (Chrome, Safari, Edge)
    if ('zoom' in body.style) {
        body.style.zoom = currentZoom;
    } else {
        // Fallback for Firefox using CSS transform
        body.style.transform = `scale(${currentZoom})`;
        body.style.transformOrigin = 'top center';
        body.style.width = `${100 / currentZoom}%`;
    }
}

// init sidebar state
applySidebar();

// ── File watching ────────────────────────────────────────
EventsOn("fileChanged", function(path) {
    // find the file in our files array by path
    var idx = files.findIndex(function(x){ return x.path === path; });
    if(idx < 0) return; // file not open, ignore

    if(!files[idx].dirty) {
        // no unsaved changes → reload silently
        ReadFile(path).then(function(content) {
            files[idx].content = content;
            if(idx === active) {
                ED.value = content;
                updateLineNums();
                updateStatus();
                renderPreview();
                renderOutline();
            }
            toast('Reloaded ' + files[idx].name);
        });
    } else {
        // has unsaved changes → show notification bar
        showNotif(path, idx);
    }
});

// ── Drag & drop ────────────────────────────────────────
document.addEventListener('dragenter', function(e){
  if(e.dataTransfer && e.dataTransfer.types && Array.from(e.dataTransfer.types).includes('Files')){
    dragN++; DOV.classList.add('on');
  }
});
document.addEventListener('dragleave', function(){
  dragN = Math.max(0, dragN-1);
  if(dragN === 0) DOV.classList.remove('on');
});

document.addEventListener('dragover', function(e){ e.preventDefault(); });

document.addEventListener('drop', async function(e){
  e.preventDefault(); dragN = 0; DOV.classList.remove('on');
  await openPicker();
});

  // ── Button wiring ──────────────────────────────────────
  document.getElementById('btn-open').addEventListener('click', openPicker);
  document.getElementById('btn-save').addEventListener('click', saveFile);
  document.getElementById('btn-saveas').addEventListener('click', saveFileAs);
  document.getElementById('btn-new').addEventListener('click', newFile);
  document.getElementById('sb-open').addEventListener('click', openPicker);
  document.getElementById('emp-open').addEventListener('click', openPicker);

  document.getElementById('btn-zoom-in').addEventListener('click', function(){ changeZoom(0.1); });
  document.getElementById('btn-zoom-out').addEventListener('click', function(){ changeZoom(-0.1); });

  document.getElementById('vt-edit').addEventListener('click',    function(){ setView('edit'); });
  document.getElementById('vt-split').addEventListener('click',   function(){ setView('split'); });
  document.getElementById('vt-preview').addEventListener('click', function(){ setView('preview'); });

  document.getElementById('f-bold').addEventListener('click',   function(){ fmt('bold'); });
  document.getElementById('f-italic').addEventListener('click', function(){ fmt('italic'); });
  document.getElementById('f-strike').addEventListener('click', function(){ fmt('strike'); });
  document.getElementById('f-code').addEventListener('click',   function(){ fmt('code'); });
  document.getElementById('f-link').addEventListener('click',   function(){ fmt('link'); });
  document.getElementById('f-h1').addEventListener('click',     function(){ fmt('h1'); });
  document.getElementById('f-h2').addEventListener('click',     function(){ fmt('h2'); });
  document.getElementById('f-h3').addEventListener('click',     function(){ fmt('h3'); });
  document.getElementById('f-ul').addEventListener('click',     function(){ fmt('ul'); });
  document.getElementById('f-ol').addEventListener('click',     function(){ fmt('ol'); });
  document.getElementById('f-task').addEventListener('click',   function(){ fmt('task'); });
  document.getElementById('f-quote').addEventListener('click',  function(){ fmt('quote'); });
  document.getElementById('f-cb').addEventListener('click',     function(){ fmt('codeblock'); });
  document.getElementById('f-hr').addEventListener('click',     function(){ fmt('hr'); });
  document.getElementById('f-table').addEventListener('click',  function(){ fmt('table'); });
  document.getElementById('f-find').addEventListener('click',   function(){ toggleSearch(); });
  document.getElementById('btn-sidebar').addEventListener('click', toggleSidebar);

  document.getElementById('notif-reload').addEventListener('click', function() {
    if(notifIdx < 0) return;
    ReadFile(notifPath).then(function(content) {
        files[notifIdx].content = content;
        files[notifIdx].dirty = false;
        if(notifIdx === active) {
            ED.value = content;
            updateTitle();
            updateLineNums();
            updateStatus();
            renderPreview();
            renderOutline();
        }
        renderSidebar();
        toast('Reloaded ' + files[notifIdx].name);
        hideNotif();
    });
  });

  document.getElementById('notif-keep').addEventListener('click', function() {
    // keep editor version, ignore disk changes
    hideNotif();
    toast('Keeping your version');
  });

  document.getElementById('notif-save').addEventListener('click', function() {
    if(notifIdx < 0) return;
    SaveFile(notifPath, files[notifIdx].content).then(function() {
        files[notifIdx].dirty = false;
        updateTitle();
        renderSidebar();
        toast('Saved ' + files[notifIdx].name);
        hideNotif();
    });
  });

  document.getElementById('notif-close').addEventListener('click', hideNotif);

  // ── Update bar buttons ───────────────────────────────────
  document.getElementById('update-download').addEventListener('click', function() {
    if(updateUrl) {
      BrowserOpenURL(updateUrl);
    }
  });

  document.getElementById('update-close').addEventListener('click', hideUpdateBar);

  // ── Global shortcuts ───────────────────────────────────
  document.addEventListener('keydown', function(e){
    if((e.ctrlKey||e.metaKey) && e.key === 'n'){ 
        e.preventDefault(); 
        newFile(); 
    }
    if((e.ctrlKey||e.metaKey) && e.key === 'o'){ 
        e.preventDefault(); 
        openPicker(); 
    }
    if((e.ctrlKey||e.metaKey) && e.key === '\\' && active >= 0){
      e.preventDefault();
      setView(view === 'split' ? 'edit' : view === 'edit' ? 'preview' : 'split');
    }
    if((e.ctrlKey||e.metaKey) && e.shiftKey && e.key === 'B'){
        e.preventDefault();
        toggleSidebar();
    }
    if((e.ctrlKey||e.metaKey) && (e.key === '=' || e.key === '+')){
        e.preventDefault();
        changeZoom(0.1);
    }
    if((e.ctrlKey||e.metaKey) && e.key === '-'){
        e.preventDefault();
        changeZoom(-0.1);
    }
    if((e.ctrlKey||e.metaKey) && e.key === 'f'){ 
      e.preventDefault(); 
      toggleSearch(); 
      return; 
    }

    // Ctrl+C
    if((e.ctrlKey||e.metaKey) && e.key === 'c'){
      e.preventDefault();
      copySelection();
      return;
    }
  });

 // ── Init ───────────────────────────────────────────────
showEmpty();
FTB.style.opacity = '.35';
FTB.style.pointerEvents = 'none';

// Set version in status bar
SB_VERSION.textContent = 'v1.7.0';

var welcome = [
  '# Welcome to Markit',
  '',
  'A **fast**, distraction-free Markdown editor for Windows.',
  'No server. No account. Your files never leave your device.',
  '',
  '## Quick Start',
  '',
  '1. Click **Open** or drag .md files onto this window',
  '2. Edit using the toolbar above or keyboard shortcuts',
  '3. Switch between Edit / Split / Preview modes (top-right)',
  '4. Click **Save** to save directly to disk',
  '',
  '## Keyboard Shortcuts',
  '',
  '| Action | Shortcut |',
  '| --- | --- |',
  '| New file | Ctrl + N |',
  '| Open file | Ctrl + O |',
  '| Save | Ctrl + S |',
  '| Bold | Ctrl + B |',
  '| Italic | Ctrl + I |',
  '| Find | Ctrl + F |',
  '| Cycle view | Ctrl + \\ |',
  '',
  '## Features',
  '',
  '- **Bold**, _italic_, ~~strikethrough~~',
  '- Inline code and fenced code blocks with syntax highlighting',
  '- Tables, blockquotes, task lists',
  '- Smart lists — press Enter to continue, empty line to stop',
  '- Resizable split pane (drag the divider)',
  '- Multiple files open at once (sidebar)',
  '',
  '## Task List',
  '',
  '- [x] Open this file',
  '- [ ] Open your own .md file',
  '- [ ] Write something',
  '',
  '> Tip: Drag the center divider left or right to resize the panes in Split mode.',
].join('\n');

// Check if launched with a file FIRST
GetStartupFile().then(function(path) {
  if(path) {
    // launched by double-clicking a .md file → open it, skip welcome
    ReadFile(path).then(function(content) {
      var name = path.split(/[\\/]/).pop();
      files.push({ name: name, content: content, dirty: false, path: path });
      StartWatching(path);
      setActive(0);
      renderSidebar();
      toast('Opened ' + name);
    });
  } else {
    // normal launch → show welcome
    files.push({name:'welcome.md', content:welcome, dirty:false});
    setActive(0);
    renderSidebar();
  }
  
  // Check for updates after app loads
  checkForUpdates();
});
})();