// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFile():Promise<string>;

export function OpenFile():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<string>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching(arg1:string):Promise<void>;
